### PR TITLE
fix body not using correct font

### LINKED ISSUE #35: body on kit-site is missing font 'Overpass'
Just noticed this while reading the kit-docs.
body-css

So the body on kit-site looks like:
sveltekit body

While on the svelte-site we have the 'Overpass' as body-font:
svelte body

### PR DESCRIPTION
**Pull request by saitheninja**
Fixes #35

### CODE REVIEW

**Comment by benmccann** [comment]
thanks! I checked this out locally and agree it looks better

**Comment by nimmolo** [comment]
I'm not seeing this fix on the live site yet. 
`body` is still using `var(--font-body)` instead of `var(--font)`

**Comment by benmccann** [comment]
I think Netlify deploys are failing until https://github.com/netlify/cli/pull/3533 is merged. Hopefully they will do that soon

**Comment by benmccann** [comment]
I think this should be deployed now

**Pull request merged**
