### PR TITLE
#1 Home page - New style 

### PR DESCRIPTION
**Pull request by rafaelcamaram**
As suggested by https://github.com/sveltejs/kit/issues/244, I'm applying the new styles on the home page. This PR aims basically update the existing components with the new style and then, in the future, I'll create new PRs in order to add the missing sections.

Figma: https://www.figma.com/file/f87psJnCeqMbUPAQABmCrN/svelte?node-id=19%3A176

### Tests
- [X] Desktop
- [X] Mid-size
- [X] Tablet
- [X] Mobile

### Preview
desktop

mid-size

mobile

### Notes

- When I was changing some files, it was formatted in order to organize the order of `script`, `html` and `style` tags -- so there are some diffs only due to this reorganization
- Does any know what would be the correct links for the `On writing`, `On overhead` and `On reativity` buttons?

### CODE REVIEW

**Comment by benmccann** [comment]
Cool! Thanks again for all your help @rafaelcamaram. Not sure if you noticed, but Figma has a different header image for the SvelteKit site. The one you used is the one that was in the svelte.dev site mock

@Rich-Harris maybe this should be something launched the day of Svelte Summit?

**Comment by rafaelcamaram** [comment]
@benmccann Oh, I just noticed that! I just pushed some changes updating the hero image and also the page content, in order to match with figma.

**Comment by benmccann** [comment]
@rafaelcamaram would you be able to rebase?

**Comment by rafaelcamaram** [comment]
@benmccann I just updated it with `master` -- please let me know if you need more adjustments on it.

**Comment by benmccann** [comment]
@rafaelcamaram Sorry but there's a new merge conflict. Would you remind rebasing one more time? Thanks again for this

**Comment by Rich-Harris** [comment]
Actually, I'm working on this locally — no need to rebase. Thank you

**Comment by rafaelcamaram** [comment]
@benmccann @Rich-Harris I pushed the commit rebasing it (I just saw the @Rich-Harris comment) -- feel free to revert it if necessary.

**Comment by Rich-Harris** [comment]
Deployed to https://kit.svelte.dev/ — thanks for the help @rafaelcamaram!

**Pull request closed without merging**
