### PR TITLE
fix: replace svelte.[assets|head|body] by sveltekit.[assets|head|body]

### PR DESCRIPTION
**Pull request by stephane-klein**
Why? See https://github.com/sveltejs/kit/pull/5016

### CODE REVIEW

**Comment by stephane-klein** [comment]
@Rich-Harris 🙂

**Comment by benmccann** [comment]
Did you test this locally? I expect that it'd break the site because you're not bumping the SvelteKit version to a version where this change is present

**Comment by stephane-klein** [comment]
@benmccann without this Pull Request commit:

```sh
$ cd sites/hn.svelte.dev
$ npm list
hn.svelte.dev@0.0.1 /home/stephane/git/github.com/sveltejs/sites/sites/hn.svelte.dev
├── @sveltejs/adapter-auto@1.0.0-next.48
├── @sveltejs/kit@1.0.0-next.345
├── prettier-plugin-svelte@2.7.0
├── prettier@2.6.2
└── svelte@3.48.0
```

```sh
$ npm run dev
```

I go to <http://127.0.0.1.3000> and I get this error:

```
Error: %svelte.assets% in src/app.html should be replaced with %sveltekit.assets%
    at load_template (file:///home/stephane/git/github.com/sveltejs/sites/sites/hn.svelte.dev/node_modules/@sveltejs/kit/dist/cli.js:792:10)
    at file:///home/stephane/git/github.com/sveltejs/sites/sites/hn.svelte.dev/node_modules/@sveltejs/kit/dist/chunks/index.js:301:24
```

More info see https://github.com/sveltejs/kit/pull/5016

@benmccann **question:** do you think that this pull request don't fix this breaking change?

**Comment by benmccann** [comment]
It's because the instructions were showing npm instead of pnpm: https://github.com/sveltejs/sites/commit/a4ffe64a8f02b7a393ee9b1849ca4d7c3261deeb

This change will break users who use pnpm because the lockfile isn't being updated as well

**Comment by benmccann** [comment]
closing in favor of https://github.com/sveltejs/sites/pull/345

**Pull request closed without merging**
