### PR TITLE
feat: show repl title on twitter meta

### PR DESCRIPTION
**Pull request by tanhauhau**
#100 for the twitter title. not sure about the images

### CODE REVIEW

**Comment by Rich-Harris** [comment]
I wonder if at this point we should just fetch the full gist in `load`, rather than fetching metadata early then later fetching the content?

**Comment by tanhauhau** [comment]
I wonder if we able to / should we differentiate boy user agent vs normal user to fetch the full gist?

Not sure how wasteful is fetching the content if it is only for generating thumbnail

**Comment by Rich-Harris** [comment]
They get cached pretty aggressively I think, so it's probably not the thing to optimise for. The only real question is whether fetching the full gist is likely to slow navigation to the point that it feels sticky, which I think is generally unlikely. And it would allow us to show a preview of the code (in an inert textarea) while the REPL loads (in a follow-up PR).

**Comment by Rich-Harris** [comment]
closing in favour of #222 and #223

**Pull request closed without merging**
