### PR TITLE
[feat] add share button in REPL

### LINKED ISSUE #95: [site] Add a share button in the REPL page controls
### Describe the problem

REPL is an awesome tool to help people learn Svelte. A good example for that is StackOverflow where I add a REPL to almost all my `svelte` related answers/questions. The problem is that there is no 'common' way to share the REPL link other than the link itself so you will see in many answers stuff like:

> Have a look at the [REPL](/repl-link)
> Here is an example: https://svelte.dev/repl/hello-world?version=3.42.2
> ...

It is therefore more or less difficult to find the final example quickly in the text where other platforms such as codesandbox  provides a button that is markdown/html that you can easily copy/paste like:

```md
[![Edit cranky-boyd-3qqnq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cranky-boyd-3qqnq?fontsize=14&hidenavigation=1&theme=dark)
```

[Edit cranky-boyd-3qqnq](https://codesandbox.io/s/cranky-boyd-3qqnq?fontsize=14&hidenavigation=1&theme=dark)

### Describe the proposed solution

Would be nice in the [REPL's AppControls](https://github.com/sveltejs/svelte/blob/master/site/src/routes/repl/%5Bid%5D/_components/AppControls/index.svelte) to add a `share` button that will open a panel that proposes you to copy the REPL link or the markdown/html button code like:

image

TODOS:

- create button svg
- host static svg on the svelte site
- add control button to open panel that includes:
  - a button to copy the URL
  - 2 textareas that contains the html/markdown of the button and a preview of it

This isn't a lot of work and I would be glad to help the svelte ecosystem that I enjoy so much. I can take care of this one if everyone agree 😄 

### Alternatives considered

n/a

### Importance

would make my life easier

### PR DESCRIPTION
**Pull request by johannchopin**
Fixes #95.

The button svg was created by using figma https://www.figma.com/file/9F50hFRCB9jdKgSvAdGNG7/svelte-edit-repl-btn?node-id=0%3A1. If a modification is needed just tell me I will add you as a collaborator.

Sep-03-2021 19-24-58

### CODE REVIEW

**Comment by johannchopin** [comment]
@benmccann Do you have suggestion to clarify the term `embed` over `share`?

**Comment by benmccann** [comment]
Here's the original PR for reference for the other reviewers: https://github.com/sveltejs/svelte/pull/6703

**Comment by Rich-Harris** [comment]
Thank you! I'm not sure it makes sense to add this to the UI until (/unless) we have a mechanism for creating embeds. We'd need to have a thorough conversation about whether that's something we want to do, and what it would involve exactly. In the meantime I think links are the appropriate way to share REPLs

**Comment by benmccann** [comment]
closing per rich's feedback in the last comment here

**Pull request closed without merging**
