### PR TITLE
feat: add ukraine support banner

### PR DESCRIPTION
**Pull request by pngwn**
This PR adds a banner at the bottom of the site showing our support for Ukraine in this time of crisis. It also provides a link directing people to support the efforts. I use the colours of the flag of Ukraine, as best I could emulate them.

I have added some padding and tweaked some heights to ensure that content is not hidden by the banner (particularly on mobile). Screenshots below
Screenshot 2022-02-28 at 11 08 53
Screenshot 2022-02-28 at 11 10 18
Screenshot 2022-02-28 at 11 10 26

### CODE REVIEW

**Comment by kevmodrome** [comment]
ACK

**Comment by dummdidumm** [comment]
This looks good on mobile everywhere except the docs. On FF the banner is placed weirdly and Chrome is completely confused

**Comment by pngwn** [comment]
@dummdidumm Do you have some screenshots? It looks okay for me on chrome. Will check FF.

I don't want to make it closable.

**Comment by pngwn** [comment]
Vedam created a nice svelte + Ukraine flag logo, should we add it? I like it.

Screenshot 2022-02-28 at 11 50 18

**Review by antony — APPROVED** [review]

**Comment by dummdidumm** [comment]
The banner stays at the bottom correctly now on mobile, but the banner hides the mobile menu that is in the bottom left.

**Comment by pngwn** [comment]
@dummdidumm Fixed in latest commit.

**Comment by denisxab** [comment]
Svelte supports fascists. I am ashamed to use this technology

**Pull request merged**
