### PR TITLE
pin site versions

### PR DESCRIPTION
**Pull request by dummdidumm**
- pin repl version so we can freely adjust it in the meantime (it has incompatible style changes)
- make hn/svelte.dev packages private so we can't accidentally publish them

### CODE REVIEW

**Comment by dummdidumm** [comment]
I don't understand the mysterious pnpm lock failure

**Comment by dummdidumm** [comment]
This is getting weirder by the minute. I removed all node_modules and the lockfile locally to start a fresh `pnpm i` and the error persists

**Comment by dummdidumm** [comment]
From tests in #439 it seems that adding back `publishDirectory: package` to the lockfile fixes the issue. No idea why

**Comment by dummdidumm** [comment]
ah yeah that's a bummer. We can't update those packages right now because they work with the new style guide now - we plan to release an overhaul of the Svelte site soon, it should be in there then.

**Comment by Tal500** [comment]
> ah yeah that's a bummer. We can't update those packages right now because they work with the new style guide now - we plan to release an overhaul of the Svelte site soon, it should be in there then.

Any update?

**Comment by benmccann** [comment]
We'll release the new site in the next week or two

**Pull request merged**
