### PR TITLE
Add svelte.dev site

### PR DESCRIPTION
**Pull request by benmccann**
The docs code formatting looks a bit funny. It matches kit.svelte.dev, but I think perhaps the svelte.dev version looks nicer

This does not migrate the homepage to use the new `site-kit`, but pulls in the old one via pnpm as `site-kit-legacy` for now

### CODE REVIEW

**Comment by Rich-Harris** [comment]
We'll need to revisit all this once the docs action has been updated and https://github.com/sveltejs/api.svelte.dev/pull/13 has been merged — right now there are some CORS errors and incorrect slugs.

In the meantime, I know it wasn't introduced by this PR but this looks super horsey, will take a look and see if we can't finesse it a bit.

image

Will take a look at the docs CSS too

**Comment by Tropix126** [comment]
The "More examples" anchor in the third section doesn't seem to be very readable on the grey background, are there plans on changing that?

**Comment by Tropix126** [comment]
Seems that the anchor color fix also affected the link to sveltejs/template below the blurbs.
image

**Comment by Rich-Harris** [comment]
Auth is now working if you use [this branch of the API](https://github.com/sveltejs/api.svelte.dev/pull/19) with the following instructions:

* add a `SECRET` to the `.env` file here (can be anything)
* add the same `SECRET` to the `[vars]` section of the API's [wrangler.toml](https://github.com/sveltejs/api.svelte.dev/pull/19/files#diff-f83f25b8d379f61ff154f7d0348243de12a09f3f768a585d9c80fbc7adcbc710R30)
* run the API locally with `npm run dev` (you will need to set up the wrangler.toml if you haven't already)
* run the site with `DOCS_PREVIEW=1 pnpm dev`

Next stop, forking/saving gists

**Comment by Rich-Harris** [comment]
Switched to using Supabase for gist storage. Much easier

**Comment by Rich-Harris** [comment]
Missing styles on tutorial: 

image

**Pull request merged**
