### PR TITLE
Add Svelte link to Kit website

### PR DESCRIPTION
**Pull request by Mlocik97**

### CODE REVIEW

**Comment by benmccann** [comment]
this seems like it might be out of place since it's text and the others are images

**Comment by Mlocik97** [comment]
I was thinking that on right side, there are "external" sources, resp. anything else than `kit.svelte.dev`, should I move it to middle?

**Comment by benmccann** [comment]
that doesn't seem right either. my inclination would be to make it a svelte logo

**Comment by Mlocik97** [comment]
I got that idea about using logo too. but the problem is Svelte and SvelteKit have same logo. For user it can be confusing?

**Comment by Mlocik97** [comment]
How about this?

**Comment by benmccann** [comment]
Can you share a screenshot?

**Comment by Mlocik97** [comment]
Snímka obrazovky z 2021-08-01 15-39-26
Snímka obrazovky z 2021-08-01 15-39-56

**Review by benmccann — APPROVED** [review]

**Comment by Mlocik97** [comment]
will this be merged? Btw. after rebase, this PR is totally mess...

**Comment by benmccann** [comment]
Fixed version of your PR here: https://github.com/sveltejs/sites/pull/62

I think you might just need to delete your `sites` repo and start over

**Pull request closed without merging**
